{% set version = "1.1.6" %}
{% set sha256 = "6fa92cde5b2caefd0d9a60336991ba42e5a7ddc3bdc36c5610451373751d0495" %}

package:
  name: snappy
  version: {{ version }}

source:
  url: https://github.com/google/snappy/archive/{{ version }}.tar.gz
  fn: {{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - skip-microbenchmarks.patch

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - msinttypes  # [win]

test:
  commands:
    - test -e $PREFIX/include/snappy.h               # [unix]
    - test -e $PREFIX/include/snappy-stubs-public.h  # [unix]
    - test -e $PREFIX/lib/libsnappy.dylib            # [osx]
    - test -e $PREFIX/lib/libsnappy.so               # [linux]

about:
  home: https://github.com/google/snappy
  summary: A fast compressor/decompressor
  license: BSD 3-clause
  license_file: COPYING
  license_family: BSD

extra:
  recipe-maintainers:
    - groutr
    - jakirkham
    - wesm
    - xhochy
