{% set version = "1.1.4" %}

package:
  name: snappy
  version: {{ version }}

source:
  url: https://github.com/google/snappy/releases/download/{{ version }}/snappy-{{ version }}.tar.gz
  fn: snappy-{{ version }}.tar.gz
  sha256: 134bfe122fd25599bb807bb8130e7ba6d9bdb851e0b16efcb83ac4f5d0b70057

build:
  number: 1
  skip: true      # [win]

requirements:
  build:
    - toolchain
    - msinttypes  # [win]
    - libtool     # [unix]
    - automake    # [unix]
    - pkg-config  # [unix]

test:
  commands:
    - test -e $PREFIX/include/snappy.h               # [unix]
    - test -e $PREFIX/include/snappy-stubs-public.h  # [unix]
    - test -e $PREFIX/lib/libsnappy.dylib            # [osx]
    - test -e $PREFIX/lib/libsnappy.a                # [unix]
    - test -e $PREFIX/lib/libsnappy.so               # [linux]

about:
  home: https://github.com/google/snappy
  summary: A fast compressor/decompressor
  license: BSD 3-clause
  license_file: COPYING
  license_family: BSD

extra:
  recipe-maintainers:
    - groutr
    - jakirkham
    - wesm
    - xhochy
