schema_version: 1

context:
  version: 1.2.2

package:
  name: snappy
  version: ${{ version }}

source:
  url: https://github.com/google/snappy/archive/${{ version }}.tar.gz
  sha256: 90f74bc1fbf78a6c56b3c4a082a05103b3a56bb17bca1a27e052ea11723292dc
  patches:
    # Name the static library snappy_static.lib on windows, to distinguish from
    # the dynamic library, since they have the same suffix there.
    # https://github.com/google/snappy/pull/57
    - patches/0001-change-static-lib-output-name-on-windows.patch
    - patches/0002-Unbundle-gtest.patch
    - patches/0003-Disable-BMI2.patch
    - patches/0004-cmake-add-option-to-enable-disable-RTTI.patch
    - patches/0005-Omit-Werror-during-compilation.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - if: win
      then: msinttypes
    - gtest 1.13.*
    - gmock
    - lz4-c
  run_exports:
    - ${{ pin_subpackage('snappy', upper_bound='x.x') }}
  ignore_run_exports:
    from_package:
      - lz4-c

tests:
  - script:
      - if: unix
        then: test -e $PREFIX/include/snappy.h
      - if: unix
        then: test -e $PREFIX/include/snappy-stubs-public.h
      - if: unix
        then: test -e $PREFIX/lib/libsnappy$SHLIB_EXT
      - if: linux
        then: test -f $PREFIX/lib/libsnappy.so.${PKG_VERSION}
      - if: osx
        then: test -f $PREFIX/lib/libsnappy.${PKG_VERSION}.dylib
      - if: win
        then: if not exist %LIBRARY_INC%\snappy.h exit 1
      - if: win
        then: if not exist %LIBRARY_INC%\snappy-stubs-public.h exit 1
      - if: win
        then: if not exist %LIBRARY_LIB%\snappy.lib exit 1
      - if: win
        then: if not exist %LIBRARY_BIN%\snappy.dll exit 1

about:
  summary: A fast compressor/decompressor
  license: BSD-3-Clause
  license_file: COPYING
  homepage: https://github.com/google/snappy

extra:
  recipe-maintainers:
    - groutr
    - jakirkham
    - wesm
    - xhochy
    - djsutherland
